language: java
jdk:
  - oraclejdk8
notifications:
  email: false

install:
      - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
script:
      # grep so that download counts don't appear in log files
      - java -jar BuildTools.jar | grep -vE "[^/ ]*/[^/ ]*\s*KB\s*$" | grep -v "^\s*$"
      - find Spigot/Spigot-Server/target/*.jar