name: IcarusMod
version: 1.0
description: The custom plugin for the Superior Freedom Network!
authors: [Wild1145, Camzie99, Hockeyfan360]
main: com.superiornetworks.icarus.IcarusMod

commands:
  icarusmod:
    description: Mostly for test usage, but will prove that the commands actually are running as expected.
    usage: /<command>
  wetoggle:
    desctiption: Toggles WorldEdit.
    usage: /<command>
  busy:
    description: Toggles your busy status to on/off
    usage: /<command>
  icmtoggle:
    description: Allows you to toggle certain aspects of the IcarusMod
    usage: /toggle <setting>
  doomhammer:
    description: Give yourself a Doom Hammer.
    usage: /doomhammer
  devmode:
    description: Allows you to turn on devmode.
    usage: /<command> <everyone|admins|developers|off>
  god:
    description: Enable/Disable God mode.
    usage: /<command> 
  report:
    description: Report another player for breaking the rules
    usage: /<command> <player> <reason>
  p:
    description: Allows you to chat with seniors in private.
    usage: /<command> <message>
  setlogin:
    description: Set your login message.
    usage: /<command> <message>
  saconfig:
    description: Admin management.
    usage: /<command> <list|add <player> [rank]|delete <player>>
