name: IcarusMod
version: 1.0
description: The custom plugin for the Superior Freedom Network!
authors: [Wild1145, Camzie99, Hockeyfan360, Paul19988]
main: com.superiornetworks.icarus.IcarusMod
softdepend: [Aero]

commands:
  icarusmod:
    description: Mostly for test usage, but will prove that the commands actually are running as expected.
    usage: /<command>
  wetoggle:
    desctiption: Toggles WE.
    usage: /<command>
  busy:
    description: Puts you in the busy status.
    usage: /<command>
  icmtoggle:
    description: Allows you to toggle certain aspects of the IcarusMod
    usage: /toggle <setting>
  doomhammer:
    description: Give yourself a DoomHammer.
    usage: /doomhammer
  devmode:
    description: Allows you to turn on devmode.
    usage: /<command> <everyone|admins|developers|off>
  god:
    description: Give yourself god mode.
    usage: /<command> 
  report:
    description: Files a report against another player
    usage: /<command> <player> <reason>
  p:
    description: Allows you to chat with seniors in private.
    usage: /<command> <message>
  setlogin:
    description: Set your login message.
    usage: /<command> <message>
  saconfig:
    description: Admin management.
    usage: /<command> <list|add <player> [rank]|delete <player>>
  opall:
    description: Op all online players.
    usage: /<command>
  tag:
    description: Set someone's tag.
    usage: /<command> <set:playername> <tag>
  say:
    description: Broadcast a message in chat.
    usage: /<command> <message>
  smite:
    description: Smite a naughty player.
    usage: /<command> <player> <reason>
